# Generated by Django 5.1.4 on 2024-12-28 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('LAYOFFS', 'Layoffs'), ('HIRING', 'Hiring'), ('HIRING_FREEZE', 'Hiring Freeze')], default='HIRING', max_length=20)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('application_url', models.URLField(blank=True)),
            ],
        ),
    ]
